name: CI

on: [push, pull_request]

jobs:
  build:
    name: GNU Emacs ${{ matrix.emacs_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version: [26.2, 26, master]
    steps:
    - name: Install GNU Emacs ${{ matrix.emacs_version }}
      run: |
        curl -fsSkL --retry 9 --retry-delay 9 -O https://github.com/npostavs/emacs-travis/releases/download/bins/emacs-bin-${{ matrix.emacs_version }}.tar.gz
        tar -xaf emacs-bin-${EMACS_VERSION}.tar.gz -C /
        export EMACS=/tmp/emacs/bin/emacs
    - uses: actions/checkout@v1
    - name: current dir
      run: pwd
    - name: Pull Elisp packages
      run: $EMACS --batch -l init.el --eval="(straight-pull-all)"
    - name: Build Elisp packages
      run: $EMACS --batch -l init.el
